name: Check Epic Free Games
on:
  schedule:
    - cron: '30 16 * * *'  # 16:30 every day (UTC)
  workflow_dispatch:  # Allow manual runs

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run notifier
        env:
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
        run: python epic_notifier.py