name: Epic Games Notifier
on:
  schedule:
    - cron: '30 16 * * *'  # 4:30 PM UTC daily
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python epic_notifier.py
        env:
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
      - name: Verify
        run: |
          echo "Cache contents:"
          [ -f "games_cache.json" ] && jq '.[].title' games_cache.json || echo "No cache"