name: Epic Games Notifier
on:
  schedule:
    - cron: '30 16 * * *'  # 4:30 PM UTC daily
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Restore game cache
        uses: actions/cache@v3
        id: game-cache
        with:
          path: games_cache.json
          key: epic-games-${{ steps.date.outputs.date }}
          restore-keys: |
            epic-games-
      
      - run: pip install requests
      
      - run: python epic_notifier.py
        env:
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
      
      - name: Save updated cache
        if: always()  # Ensure save even if script fails
        uses: actions/cache@v3
        with:
          path: games_cache.json
          key: epic-games-${{ steps.date.outputs.date }}
      
      - name: Debug
        run: |
          echo "=== Cache Status ==="
          echo "Cache hit:" ${{ steps.game-cache.outputs.cache-hit }}
          echo "=== Cache Contents ==="
          [ -f "games_cache.json" ] && jq '.' games_cache.json || echo "No cache"
          echo "=== API Status ==="
          curl -s "https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=zh-CN" | jq '.data.Catalog.searchStore.elements[].title'